name: Build and run Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_automation:

    runs-on: [windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Install dependencies with NuGet
      run: nuget restore Tetris.sln
      
    - name: Build
      run: msbuild Tetris.sln
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
