name: Build and Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: ms-build
      uses: microsoft/setup-msbuild@v1
      

      
    - name: Build
      run: msbuild Tetris.sln
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
